### ISSUE TITLE
Could not run this at all. There were huge issues with import urllib

### ISSUE THREAD

**Issue by MeghanaSudhindra** [SochInc/VDR#2]

**Comment by MeghanaSudhindra** [comment]
Exception in Tkinter callback
Traceback (most recent call last):
  File "c:\python27\lib\lib-tk\Tkinter.py", line 1541, in __call__
    return self.func(*args)
  File "<ipython-input-5-059d3749177f>", line 11, in callback
    cp.capture()
  File "MainCam.py", line 15, in capture
    stream = urllib.request.urlopen('http://10.42.0.205:8080/video')
NameError: global name 'urllib' is not defined
Exception in Tkinter callback
Traceback (most recent call last):
  File "c:\python27\lib\lib-tk\Tkinter.py", line 1541, in __call__
    return self.func(*args)
  File "<ipython-input-5-059d3749177f>", line 11, in callback
    cp.capture()
  File "MainCam.py", line 15, in capture
    stream = urllib.request.urlopen('http://10.42.0.205:8080/video')
NameError: global name 'urllib' is not defined

**Comment by esctaticdivyansh** [comment]
stream = urllib.request.urlopen('http://10.42.0.205:8080/video') what is this line and where is it taking us?

**Comment by l3lackcurtains** [comment]
Use your local address.
